services:
  mywebsite:
    build: .
    container_name: mywebsite
    ports:
      - "${BIND_PORT}:8081"
    environment:
      - API_KEY=${API_KEY}
      - BIND_PORT=${BIND_PORT}
      - BIND_ADDRESS=${BIND_ADDRESS}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DBNAME=${MONGO_DB_NAME}
    volumes:
      - ./public:/app/public
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mywebsite-mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:


